--- !ruby/object:RI::MethodDescription 
aliases: []

block_params: 
comment: 
- !ruby/struct:SM::Flow::P 
  body: Configure this State instance with the Hash <em>opts</em>, and return itself.
full_name: JSON::Ext::Generator::State#configure
is_singleton: false
name: configure
params: " configure(opts)\n"
visibility: public
